### ISSUE TITLE
Training results of COCO

### ISSUE THREAD

**Issue by edwintenagyei367** [mlpc-ucsd/PRTR#10]
Hello, This is an amazing work , however, I faced a challenge while training the model on the COCO dataset. The below picture shows the results reported. What could be the reason ? Hoping to receive a reply from you.Thank you.
![743423802](https://user-images.githubusercontent.com/25607474/146945791-075710c0-f8a4-4ffa-97f5-11440ec8f0bf.jpg)

**Comment by Ning-yuan118** [comment]
I face the same problem, did you solve it?

**Comment by zx1239856** [comment]
Turns out the OP was loading our weights while using the 1e-4 LR, which is intended for training with ImageNet weights from scratch. Please open new issues if there are new problems arising.

**Comment by Sherryxingxing** [comment]
> I face the same problem, did you solve it?
Have you solved it？

**Comment by Sherryxingxing** [comment]
> Hello, This is an amazing work , however, I faced a challenge while training the model on the COCO dataset. The below picture shows the results reported. What could be the reason ? Hoping to receive a reply from you.Thank you. ![743423802](https://user-images.githubusercontent.com/25607474/146945791-075710c0-f8a4-4ffa-97f5-11440ec8f0bf.jpg)

Have you solved this problem
