### ISSUE TITLE
How do you discard unmatched queries

### ISSUE THREAD

**Issue by ziqi123** [mlpc-ucsd/PRTR#12]
Hello,
In training stage of person detection Transformer, how do you discard unmatched queries ? I don't see the code of this stage.
Is the "person per image" in your code equals to 5  or less in End-to-end variant?

**Comment by zx1239856** [comment]
During training, the unmatched queries are not discarded. Different loss functions are applied for matched and unmatched queries. Please read the main paper for details.

For the end-to-end variant, the person per image depends on your GPU memory. If working with a smaller memory size, one way is to 
randomly sample some person boxes.
