### ISSUE TITLE
error: command 'g++' failed with exit status 1

### ISSUE THREAD

**Issue by Sherryxingxing** [mlpc-ucsd/PRTR#13]
/home/sherry/anaconda3/compiler_compat/ld: cannot find -lcudart
collect2: error: ld returned 1 exit status
error: command 'g++' failed with exit status 1

When I run bash make.sh, this problem occurs. How to deal with it?

**Comment by zx1239856** [comment]
Please specify your CUDA version and ensure you use the same version as us and the libraries are fully installed.

**Comment by Sherryxingxing** [comment]
My configuration is as follows：
ubuntu：20.04
cuda:11.0.207
cudnn：8.05
torch：1.71+cu110
turchvision：0.8.2+cu110

**Comment by Sherryxingxing** [comment]
> Please specify your CUDA version and ensure you use the same version as us and the libraries are fully installed.
My configuration is as follows：
ubuntu：20.04
cuda:11.0.207
cudnn：8.05
torch：1.71+cu110
turchvision：0.8.2+cu110

**Comment by zx1239856** [comment]
We tried on the same CUDA major version (we use CUDA 11.5) and we were able to build successfully. 
The issue is most likely due to the improper CUDA installation. We recommend you use anaconda to 
avoid such problems.

**Comment by Sherryxingxing** [comment]
Thank you, it should be the problem of cuda, I use the cloud server tried, have been able to run smoothly.
Thank you!
By the way, I also want to ask, how to visualize the test results?
There is a skeleton in can see the pictures?
If I want to use video test what should I do?

**Comment by Sherryxingxing** [comment]
> We tried on the same CUDA major version (we use CUDA 11.5) and we were able to build successfully. The issue is most likely due to the improper CUDA installation. We recommend you use anaconda to avoid such problems.

Thank you, it should be the problem of cuda, I use the cloud server tried, have been able to run smoothly.
Thank you!
By the way, I also want to ask, how to visualize the test results?
There is a skeleton in can see the pictures?
If I want to use video test what should I do?
