### ISSUE TITLE
Sequential Transformers

### ISSUE THREAD

**Issue by lxy5513** [mlpc-ucsd/PRTR#2]
Amazing for your Sequential Transformers, have you plan to release Sequential Transformers code ?

**Comment by ricolike** [comment]
Hi @lxy5513, please refer to [annotated_prtr.ipynb](sequential/annotated_prtr.ipynb) for implementation of the sequential (end-to-end) model variant.

**Comment by lxy5513** [comment]
Thanks for your kind reply @ricolike .
In `annotated_prtr.ipynb`, I find the architecture code, 
```
Class PRTR_sequential needs the following arguments:
backbone: a customizable CNN backbone which returns a pyramid of feature maps with different spatial size
transformer: a customizable Transformer for person detection (1st Transformer)
transformer_kpt: a customizable Transformer for keypoint detection (2nd Transformer)
level: from which layers of pyramid we will extract features
x_res: the width of STN-cropped featrure map fed to 2nd Transformer
y_res: the height of STN-cropped featrure map fed to 2nd Transformer
```
but, I can't find those specific implementation.

**Comment by lxy5513** [comment]
Wow, thanks for your detailed explanation, I will try the amazing architecture. Appreciate it.

**Comment by ricolike** [comment]
solved
