### ISSUE TITLE
Person-detection Transformer in two-stage variant

### ISSUE THREAD

**Issue by Charleshhy** [mlpc-ucsd/PRTR#3]
Hi,

Thanks for the nice work, I am just get a little bit confused about the implementation. The proposed person-detection transformer is not used in the two-stage variant. Instead, person detection results from another detector and gt bounding boxes are used in COCO and MPII, respectively.

Am I understanding it right? If the proposed person-detection transformer is used, can you point it out where and how? Thanks a lot!

Regards,
Charles

**Comment by ricolike** [comment]
Hi Charles, 
Thanks for your interests in PRTR. You are half-correct here.  
For both COCO and MPII, we used ground truth person bounding boxes for training but fintuned person detection Transformer outputs in evaluation stage. Details of finetuning process can be found at _Person-detection Transformer finetuning_ of 4.1 Experiment Setup in paper.
