### ISSUE TITLE
HRnet作为backbone 训练时结果异常

### ISSUE THREAD

**Issue by sheeranshan** [mlpc-ucsd/PRTR#4]
mpii作为训练集的情况下， mean总是在5.徘徊，训练很多轮还是这样。麻烦请指导下是哪里的问题，谢谢

训练日志链接[https://pan.baidu.com/s/19fSdYp-FR-SNB42NVOcE0g](url)
提取码1111

**Comment by zx1239856** [comment]
I'm closing this issue as we don't have access to the file in the link provided.
