### ISSUE TITLE
Squential Transformer training 

### ISSUE THREAD

**Issue by abhigoku10** [mlpc-ucsd/PRTR#5]
Hi thanks for open-sourcing the code, work is really good i have few queries 
1. Can we train the sequential transformer separately as  i need to train it on the WIDER attribute dataset 
2. can we replace the keypoint detector with an attribute classifier so obtain the person attributes 
3. What is the inference time taken for sequential transformer 

Thanks in advance

**Comment by likenneth** [comment]
Glad to help!

Yes, you can train the person detector, freeze its weights or not, and then train a keypoint detector (like what we did) or attribute classifier or something else on top of it.

I did not record the time but I remember we were not troubled by this. If you have tried your data on heatmap-based keypoint detector (HR-Net etc.), it should be fine with our model as well. We also have NN inference overheads, but not the post-processing which can be time-costing.

**Comment by abhigoku10** [comment]
@likenneth  Thanks for your response can you pls share the training pipeline for sequential transformer ??

**Comment by likenneth** [comment]
Hi @abhigoku10, please refer to [annotated_prtr.ipynb](https://github.com/mlpc-ucsd/PRTR/blob/main/sequential/annotated_prtr.ipynb) for implementation of the sequential (end-to-end) model variant.

**Comment by abhigoku10** [comment]
@likenneth thanks for the response 
1. similar to two cascade dont we have training pipeline for sequential transformer 
2. is data preparation same for both the types of transformers 
3. in sequential your using stn to crop the entire person from the image right

**Comment by likenneth** [comment]
Hi, 

1. Both varients are _cascade_, the two-stage one has code.
2. Yes.
3. Yes. 

I suggest checking the paper first for your questions, where you can find more detailed answer by yourself if it is not related to implementation. Feel free to come to me if any question presists.

**Comment by likenneth** [comment]
Hi, 

1. Both sequential and two-stage are termed _cacade_ in our paper. For the two-stage one, you can find training pipeline [here](https://github.com/mlpc-ucsd/PRTR/tree/main/two_stage).
2. Yes.
3. Yes.

Welcome to check our paper.
