### ISSUE TITLE
Person-detection Transformer

### ISSUE THREAD

**Issue by EckoTan0804** [mlpc-ucsd/PRTR#7]
Hello,

I've read the PRTR paper and the issue #3. However, I am still not 100% clear about how to fine-tune DETR for person detection by myself. Can you please share more details about it, e.g., how to adjust DETR as well as data loading of COCO for only detecting persons?
Btw have you also fine-tuned deformable DETR for person detection?

Thanks in advance!

**Comment by zx1239856** [comment]
We didn't try to fine-tune the deformable DETR for person detection.
For the two-stage variant, you can use any off-the-shelf detector, or fine-tune the DETR. You can 
make it only focus on person detection by training it on COCO human pose dataset.
