### ISSUE TITLE
Confuesd about Positional encoding and Crop data

### ISSUE THREAD

**Issue by leijue222** [mlpc-ucsd/PRTR#9]
1. positional encoding 
> ## Description of the paper ##
> absolute positional encoding （DETR Detector）
> positional encoding relative to corresponding bounding boxes.（Pose transformer ）

Do two-stage transformers use the same positional encoding of sine? (Refer to the code [here](https://github.com/mlpc-ucsd/PRTR/blob/64970b88e204fbdba757303747fe7370540aa09a/two_stage/lib/models/positional_encoding.py#L81))

2. Crop data
After debugging, I found that when training pose_transformer: the human box is not detected by DETR, but the box is labeled with COCO. (Refer to the [data load function](https://github.com/mlpc-ucsd/PRTR/blob/64970b88e204fbdba757303747fe7370540aa09a/two_stage/lib/dataset/coco.py#L143)) 
That means people are predicting one by one. And I noticed that there is a scale operation when cropping, which makes the result after Crop more likely to contain multiple people, but supervision is a pose of one person. 
Debug trainning data image:
![QQ截图20211021185505](https://user-images.githubusercontent.com/30276789/138264287-1a42ce8e-e793-4f1e-8190-98af017a10e5.png)

So I am curious about how to do parallel detection after cropping when multiple people are detected.

**Comment by zx1239856** [comment]
1. We use the same positional encoding scheme as in DETR (https://github.com/facebookresearch/detr/blob/eb9f7e03ed8e2ed2cd55528989fe7df890bc3fc0/models/position_encoding.py#L28). Positional encoding relative to the bounding box just means we use the image cropped by the bbox for the encoding. In that case, the range for normalized `x_embed`/`y_embed` would be [0,1]. 
Another scheme would be to use the original image to generate the encoding, then crop it with the bbox. This is not used in our paper. The range for normalized `x_embed`/`y_embed` then would be [x1/w, x2/w], [y1/h, y2/h]. (assume the XYXY bbox is [x1, y1, x2, y2])

2. We use pre-generated boxes for the two-stage scheme, as mentioned in the paper.
    For complex cases with multiple people cluttering or occluding, two-stage cropping would not work well, as it's hard to isolate a single person just by cropping. This is definitely a major limitation for such architecture.

**Comment by leijue222** [comment]
Thank you!
By the way, How long did it take you to train 200 epochs? 
And which GPU did you use and how many?

**Comment by zx1239856** [comment]
Please refer to our training logs 

https://github.com/mlpc-ucsd/PRTR/tree/main/two_stage#train-logs

**Comment by leijue222** [comment]
Thanks!!
> Hrnet_w32_384x288_adamw_lr1e-4
> 140 Epochs
> Begin: 2021-01-19 17:51:43
> End: 2021-01-24 04:57:51

It took nearly 5 days to train 140 epochs on 4×GPUS.
May I ask which GPU version you used? (V100, 2080Ti or 1080Ti)?
